name: Feature Request
description: Proposer une amélioration
title: "[FEATURE] "
labels: ["enhancement", "triage"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problème / besoin
      description: Quel problème veux-tu résoudre ?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Solution proposée
      description: Comment imagines-tu la fonctionnalité ?
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priorité
      options:
        - Nice to have
        - Utile
        - Important
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Informations additionnelles
